export default {
  CHANGE_ROUTE_DATA: "CHANGE_ROUTE_DATA",
  RESET_BETA: "RESET_ BETA",
  SELECT_BETA: "SELECT_BETA",
  SELECT_BOULDER: "SELECT_BOULDER",
  SELECT_ROUTE: "SELECT_ROUTE",
  SELECT_HOLD: "SELECT_HOLD"
}
