export default {
  CHANGE_ROUTE_DATA: "CHANGE_ROUTE_DATA",
  CLEAR_BETA: "CLEAR:BETA",
  CLEAR_ROUTE: "CLEAR_ROUTE",
  CLEAR_ROUTE_DATA: "CLEAR_ROUTE_DATA",
  SELECT_BETA: "SELECT_BETA",
  SELECT_BOULDER: "SELECT_BOULDER",
  SELECT_ROUTE: "SELECT_ROUTE",
  SELECT_HOLD: "SELECT_HOLD"
}
